apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: firebird
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: iad.ocir.io/idrnu3akjpv5/rabbitmq:3-management
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: stonezhong
          - name: RABBITMQ_DEFAULT_PASS
            value: changeme
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: firebird
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector: 
    app:  rabbitmq
  ports:
  - name: tcp-5672
    port: 5672
    targetPort: 5672
  - name: tcp-15672
    port: 80
    targetPort: 15672
