apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: firebird
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: iad.ocir.io/idrnu3akjpv5/redis-stack-server:6.2.6-v8
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: firebird
spec:
  selector: 
    app:  rabbitmq
  ports:
  - name: tcp-5672
    protocol: TCP
    port: 5672
    targetPort: 5672
