apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: firebird
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: iad.ocir.io/idrnu3akjpv5/zookeeper:3.8.1
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: firebird
spec:
  selector: 
    app:  zookeeper
  ports:
  - name: tcp-2181
    protocol: TCP
    port: 2181
    targetPort: 2181
  - name: tcp-2888
    protocol: TCP
    port: 2888
    targetPort: 2888
  - name: tcp-3888
    protocol: TCP
    port: 3888
    targetPort: 3888
  - name: tcp-8080
    protocol: TCP
    port: 8080
    targetPort: 8080
