apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: firebird
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: iad.ocir.io/idrnu3akjpv5/firebird-app
        command: ["python", "-u"]
        args: ["/usr/local/lib/python3.11/site-packages/firebird/cmd_tools/executor.py", "-pid", "test"]
    
